### ISSUE TITLE
[Ruby]<span class="matching-1">

### ISSUE THREAD

**Issue by Redouane555** [replit/repl.it#132] opened 2015-03-04 13:00 UTC
In the Ruby interpreter (http://repl.it/languages/Ruby ):
I typed the following code:
(-100..100).each {|x| 
   y = -x-2; 
   z = x+2*y; 
   puts"#{x};#{y};#{z}" if (z == 4 \* x-y)
}

And I got  <span class="matching-1"> in the lines 4 and 5.

(Don't paste the code,try to type it)

**Comment by amasad** [comment] 2015-03-05 05:13
Runs the same for me on my computer and on repl.it
http://repl.it/cpE
Can you be more clear about what the failure is?

**Comment by SomeRed** [comment] 2015-03-08 18:02
EDIT: found an easier way to reproduce the issue:type this line on the right panel:puts"#{x};"don't paste it,type it.The '}' will get highlightened in purple,then when you'll type the ';',it'll show the html line.


     Le Jeudi 5 mars 2015 6h13, Amjad Masad <notifications@github.com> a écrit :
   

 Runs the same for me on my computer and on repl.it
http://repl.it/cpE
Can you be more clear about what the failure is?—

**Comment by timmyichen** [comment] 2017-12-20 21:31
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, this appears to no longer be an issue.

**Closed by timmyichen** 2017-12-20 21:31 UTC
