### ISSUE TITLE
Python 3 Has An Error 1006 Every Time I Go On It

### ISSUE THREAD

**Issue by Eburf17** [replit/repl.it#155] opened 2016-01-17 00:21 UTC
I've tried everything to fix it, from restarting my computer to unpluging my router and even making a new repl.it account.  But it is not only Python is is Java too.

**Comment by amasad** [comment] 2016-01-17 05:51
That usually means that it cannot connect. Are you behind a firewall?

**Comment by januryga** [comment] 2016-01-24 15:35
I have the same issue. Happens on my phone (Chrome), regardless of whether I'm on wifi or LTE.

**Comment by amasad** [comment] 2016-01-24 21:58
Can you please go to this diagnosis page and let me know the results? It
should tell us if your browser/connection supports websocketd

http://websocketstest.com/

**Comment by CrazyCasta** [comment] 2016-01-25 19:35
I'm on Chrome on Android and here's my results: http://websocketstest.com/result/688468 

I've tried both Java and Python and neither works.

**Comment by CrazyCasta** [comment] 2016-01-25 19:36
P.S. Just to be clear the 1006 error is what I'm getting.

**Comment by Eburf17** [comment] 2016-01-26 14:31
Okay I will try the web socket. Thanks for the help.

**Comment by Eburf17** [comment] 2016-01-26 21:45
http://websocketstest.com/result/689195

Those are my results

**Comment by Eburf17** [comment] 2016-01-26 23:20
I am behind Windows Firewall With Advanced Security.

**Comment by amasad** [comment] 2016-01-26 23:26
@eburf17 can you try disabling it for a minute to check if it's the problem? This would help a lot with the troubleshooting! Thanks for all the info so far

**Comment by amasad** [comment] 2016-01-26 23:34
@masad-frost can you check this on windows?

**Comment by maelruanaidh** [comment] 2016-01-26 23:45
Also getting this error as well from a Mac under a university firewall currently. Will test at another location on a windows PC later tonight without the firewall.

**Comment by amasad** [comment] 2016-01-26 23:48
@maelruanaidh Can you also run the diagnostic test and report back? http://websocketstest.com/ 
Thanks

**Comment by maelruanaidh** [comment] 2016-01-26 23:51
Real-Time Web test – Does HTML5 WebSockets work for you?

WebSockets seem to
Work for You!

    Environment
    WebSockets supported 	Yes✔
    HTTP Proxy 	No
    WebSocket protocol version 	rfc-6455
    WebSockets (Port 80)
    Connected	Yes✔
    Data Receive	Yes✔
    Data Send	Yes✔
    Echo Test	Yes✔
    Server time	2016/1/26 23:49:37
    WebSockets (Port 443)
    Connected	Yes✔
    Data Receive	Yes✔
    Data Send	Yes✔
    Echo Test	Yes✔
    Server time	2016/1/26 23:49:37
    WebSockets (Port 8080)
    Connected	Yes✔
    Data Receive	Yes✔
    Data Send	Yes✔
    Echo Test	Yes✔
    Server time	2016/1/26 23:49:37
    WebSockets (Port 443, SSL)
    Connected	Yes✔
    Data Receive	Yes✔
    Data Send	Yes✔
    Echo Test	Yes✔
    Server time	2016/1/26 23:49:37

    Additional Details
    Antivirus Name 		
    Antivirus version 		

Result ID: 689245

This test was created to study implications of using WebSockets in real-life scenarios. Having WebSockets supported in your browser doesn't guarantee they will work for you. Antiviruses, firewalls and HTTP proxies may interfere WebSocket connections, sometimes rendering them useless.

On this page you can see how well WebSockets can work with your Internet Connection, your Antivirus and all other software you have. The test checks WebSocket operation by connecting to the WebSocket-enabled server and exchanging the data. The time displayed in "Server time" line should update every second if WebSockets work for you.

This server supports WebSocket Protocol proposed standard (RFC-6455, December 2011), per-frame-deflate-extension-00 draft, older websocket drafts as well as even older Hixie drafts 75 and 76 (August 2010) with the fix for HTTP reverse proxies.

Jan 31, 2011 - version 1.2

This test was created by Mikhail Platov, inspired by HTML5 test created by Niels Leenheer.
Hosted by:
Godville

Aggregated test results.

**Comment by amasad** [comment] 2016-01-27 00:21
One more thing to try. Our servers that execute the code are at a different domain from the website. Maybe your firewalls are blocking it. Can you try going to:
https://eval.repl.it/
http://eval.repl.it/

It should say `ヾ(*ФωФ)βyё βyё☆彡` Let me know whether you get that.

**Comment by masad-frost** [comment] 2016-01-27 06:38
Unable to reproduce on windows with any realistic firewall rules.

I'll hopefully be able to reproduce behind a University or a company proxy/firewall soon.

**Comment by maelruanaidh** [comment] 2016-01-27 14:15
@amasad 

Unfortunately, I left campus before I could test your link there, but I can try again on Thursday evening. However, I've successfully tested access to both repl.it itself, and the eval.repl.it from the following devices. 

1. Nexus 6p - Chrome - mobile
2. Home PC - Win10 - Chrome - no firewall
3. Work PC - Win7 - Chrome - w. corp. firewall

Thank you for your help.

**Comment by amasad** [comment] 2016-01-27 17:38
Thanks a lot, Bam. Your help is appreciated

**Comment by januryga** [comment] 2016-01-27 19:06
http://websocketstest.com/result/689866

I'm using the latest Chrome on Android 6.0. To make things weirder, it
doesn't work in Firefox either.

**Comment by Eburf17** [comment] 2016-01-27 23:00
I turned my firewall off and it still did not work, it had the same error.

**Comment by Eburf17** [comment] 2016-01-27 23:06
@amasad

I got the  ヾ(*ФωФ)βyё βyё☆彡

**Comment by Eburf17** [comment] 2016-01-27 23:12
My python works now after I turned my firewall back on it now appears to be working with no errors so far.  Thank you all so much!

**Comment by maelruanaidh** [comment] 2016-01-29 05:54
@amasad 

Off topic, but is there a kill function for accidental infinite loops?

**Comment by amasad** [comment] 2016-01-30 02:29
We already have this in place where it should prompt you to kill if it
takes too long. If that's not the case then it must be a bug. Can you send
me example code where we don't catch infinite loops?

**Comment by amasad** [comment] 2016-02-03 00:29
let's keep this open for now make sure we have a solution for this

**Comment by Eburf17** [comment] 2016-02-03 00:31
Ok sorry, just no one said anything for i while so I thoght everyone fixed it.

**Comment by MarquisIP** [comment] 2016-02-25 08:56
Apologies for bumping an older thread, but we have encountered a similar situation to that described by the OP, and I believe I might be able to offer some additional, useful information.

We sit behind a firewall provided by our Local Education Authority (we're UK-based) and noticed we received the 1006 error on our newly enrolled Chromebooks, but not when using the Chrome browser on our existing fleet of computers and laptops.

After a little bit of poking around, we believe the error (at least in our case), stems from the fact that under a Windows based system, when you apply proxy settings to all protocols (HTTP, HTTPS, SOCKS etc), it does not actually populate the entry for SOCKs Host (the user must *always* entry it manually), however we found that under Google Apps for Education's device management console (used for managing settings on enrolled devices), when you apply to all protocols, it *does* populate the SOCKS Host entry with the same settings. We believe the problem arises if your filtering provider's settings for SOCKS Host are different from the generic proxy settings, or if the filtering provider has not actually configured SOCKS Host settings. I would also assume that, as Chromebooks (or more correctly, Chrome OS) will not accept a null entry for SOCKS Host, that it is probably the same for other systems manufactured by Google, such as Android, which might go some way to explaining why this error is occurring on some of the aforementioned systems. Additionally, it may well be that non-Google systems, sitting behind firewalls and giving the same error, suffer from a not too dissimilar problem...

Anywho, hope the above information is useful!

**Comment by amasad** [comment] 2016-02-25 09:01
Thanks for the investigation @MarquisIP!

Where you able to make it work? Also, can you explain what is meant by
SOCKS?

**Comment by MarquisIP** [comment] 2016-02-25 09:12
Unfortunately we have not yet managed to resolve the issue: I'm waiting for additional information from our filtering provider as to whether or not they have configured for SOCKs and if they have, what the correct proxy settings should be.

Sorry, I meant SOCKs as shorthand for websocket (https://en.wikipedia.org/wiki/SOCKS), which is how it tends to be referred to in most devices' proxy settings - I know you use websocket to pass information between the browser implementation of Python, and the servers that actually run the code. As per my post above, I believe the problem occurs when the end user is sat behind a firewall that either isn't correctly configured for websocket traffic, or where the proxy settings for handling websocket traffic are different to the generic settings the end user has applied to all the other usual protocols (HTTP, HTTPS, etc).

I'm hoping, that when we have the correct settings from our filtering provider, or they have actually set up for websocket traffic, we should be able to use REPL on our Chromebooks without any further problems.

It's a fantastic resource by the way - As a teacher, I've found it an absolute lifesaver, so thank you!

**Comment by amasad** [comment] 2016-02-25 09:18
Please do let us know if you solve it. Meanwhile I'll try to provide a
meaningful fallback for users behind firewalls like yourself. Something
that potentially can runs the code but doesn't necessarily open in an
interactive session (which is what requires the long living session).

How often does your students use the console interactively vs just run the
code in the editor?

**Comment by MarquisIP** [comment] 2016-02-25 09:26
I'll keep you updated (although our filtering provider work at a much slower pace!).

We're currently using REPL on a weekly basis with our Year 6 students: The sessions tend to have a combination of coding in the editor, and interactive use of the console (we use a lot of Code Club materials: https://codeclubprojects.org/en-GB/). One of the reasons we like using REPL, is because you've got that flexibility. Plus we like the fact that the in-browser GUI is nice and clean. Am keeping a watchful eye on your plans to implement teacher and student accounts!

**Comment by amasad** [comment] 2016-02-27 22:15
Hey guys, I just pushed a fix that would detect if you cannot connect via websockets and fallsback to using polling to emulate websocket behavior. It should provide the same user experience. It may only be a little bit slower.

Can you test and let me know if you it works?

Thanks!

**Comment by MarquisIP** [comment] 2016-03-01 08:13
Hi Amasad,

I can confirm that the new fix appears to work for us - It takes about 30-45 seconds to detect and make the switch, and running code is not quite as quick as via websockets, but it certainly does the job, thank you! I'll be putting it under some stress this afternoon (GMT), as I'll have a class of 30 pupils accessing it - I'll let you know how we get on.

Unfortunately on my end, I am still waiting for a response from our filtering provider - It seems the bigger the company, the slower the technical support...

**Comment by maelruanaidh** [comment] 2016-04-12 20:51
Hey just wanted to report a possibly related error from the same school internet that caused the previous one. At the moment when I go to run my code it provides an "Error connecting Error: transport error" without running anything.

Please let me know if you would like me to create a new ticket.

**Comment by amasad** [comment] 2016-04-12 20:58
Can you send us an email? contact@repl.it
It's easier to talk there. Thanks

**Comment by timmyichen** [comment] 2017-12-20 21:37
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

**Closed by timmyichen** 2017-12-20 21:37 UTC
